### ISSUE TITLE
No Firing sound on some weapons

### ISSUE THREAD

**Issue by bank2014** [BrettRyland/BDArmory#394]
my KSP ver 1.12.3 (lastest)
Almost all super high fire rate miniguns do not produce sounds

**Comment by BrettRyland** [comment]
There is an infamous "sound bug" in KSP where many sounds stop working sometimes when a lot is happening on-screen.
If that's not the situation for you, then make sure that the sound files for the weapons are in the correct location (CIWS uses the sounds files `GameData/BDArmory/Parts/gau-8/sounds/GAU8Cannon.ogg` and `GameData/BDArmory/Parts/gau-8/sounds/GAU8End.ogg` and the Howitzer uses `GameData/BDArmory/Parts/m1Abrams/sounds/shot.ogg`. If these are not in the correct location, then BDArmory is likely not installed correctly and you should re-install it.

**Comment by bank2014** [comment]
I just checked it and the ogg files are in place, and they are playable too
This problem only appears on BDA plus not BDAc.

**Comment by BrettRyland** [comment]
Can you attach your `KSP.log` file (from the main KSP folder) after having fired the CIWS and not hearing the sounds and then changing scenes (e.g., going back to the Space Center, reverting to the SPH or quitting  — this is just to ensure that anything relevant gets written to the log file)? That may give a clue as to why those sounds aren't working for you, since they work fine for me.

**Comment by Sphr3000** [comment]
I also struggle with this issiue. I have checked the ksp log and it shows this message:
"Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (bahaHiddenVulcan)"

**Comment by BrettRyland** [comment]
> I also struggle with this issiue. I have checked the ksp log and it shows this message: "Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (bahaHiddenVulcan)"

OK, can you attach your entire KSP.log file from an instance where this happens?

**Comment by Sphr3000** [comment]
> OK, can you attach your entire KSP.log file from an instance where this happens?

Sure thing, here it is.
[KSP.log](https://github.com/BrettRyland/BDArmory/files/9275028/KSP.log)
.

**Comment by BrettRyland** [comment]
Also, are you using any other mods that do something to the audio? According to this [post](https://answers.unity.com/questions/259251/audiohighpassfilter-with-multiple-audiosource.html), the "Only custom filters can be played." can be triggered by adding an audio source that plays initially and is then removed to a game object with an existing audio source and filter.

**Comment by Sphr3000** [comment]
Unelss Chatterer counts I do not use  any audio altering mods.
If it helps in any way, the 25mm cannon works and sounds just fine.

**Comment by BrettRyland** [comment]
I wouldn't think Chatterer would affect it, since that wouldn't be adjusting individual parts.
I see in the log that each series of "Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (bahaHiddenVulcan)." is followed by a "PlayOneShot was called with a null AudioClip.", so it looks like the audio source is losing the audio clip that should be attached to it for some reason. I'll have to examine the log a bit more closely to see if there's any hint as to why that's happening, since it's definitely showing earlier in the log that the audio clips are being loaded.

**Comment by bank2014** [comment]
I've tried running with only BDA plus, no other mods installed, but still same

**Comment by bank2014** [comment]
[KSP.log](https://github.com/BrettRyland/BDArmory/files/9275063/KSP.log)

**Comment by BrettRyland** [comment]
Thanks. It's interesting to see the `KSPCF:MemoryLeaks` entries for BDA+. I'll add those to the things to be fixed.
Otherwise, I'm seeing the same pattern of multiple "Only custom filters can be played." messages and a "PlayOneShot was called with a null AudioClip." message in your log, but no explanation as to why yet.

**Comment by bank2014** [comment]
Rate of fire actually doesn't matter(And calibers too). my 25mm GAU-22 do produce sounds which is a minigun

**Comment by bank2014** [comment]
Just tested out 5 guns in "guns" category 
* No firing & firing_end & overheat sound: 50cal browning,  GAU-8 30mm, Vulcan 
* normal : Vulcan, energy field manipulator 
I also changed  ***fireSoundPath*** in .cfg of those errored guns to working one's audio path, but still nothing changes. so it's not hard- coded path related bug or audio file problems I think

**Comment by bank2014** [comment]
Turns out **fireSoundPath** in some of weapon CFGs is giving wrong path parameters to GameDatabase.Instance.GetAudioClip(). which should be in upper case, "Sound" not "sound"
thats why some guns do have sound because they didn't have "Sound" directory 
![화면 캡처 2022-08-07 030004](https://user-images.githubusercontent.com/69072509/183260654-4c410c46-9724-4c0d-8051-3eb21593ce04.png)
![화면 캡처 2022-08-07 030125](https://user-images.githubusercontent.com/69072509/183260724-c5bfa80d-776e-4e96-a4c0-7f278fdfe28c.png)
 
 I'll PR the fix later

**Comment by BrettRyland** [comment]
Well, that's strange, because in dev the `BDArmory/Parts/50CalTurret/sounds/` folder is lowercase (i.e., matching what's in the config 50cal.cfg), so something is messing with the installation of BDArmory.

Looking at the CKAN zip file, this appears to be caused by their repackaging of the zip file on SpaceDock, they've capitalised the `sounds` folder within each part. The only ones that are capitalised in dev are the `browninganm2`, the `m230ChainGun` and the `oMillennium`.
Can you reinstall from SpaceDock (https://spacedock.info/mod/2487/BDArmory%20Plus) and check that it then works for you?

**Comment by bank2014** [comment]
Then, Simply removing all the sound folders on each part and apply changes on cfg will fix it.  I'm doing that rn 
Changing to upper case works for me.
if you don't mind, I can do that for you since it's a laborious work

+ I'll be waiting for CKAN release because I only use CKAN to install mods. I don't manully install them

**Comment by BrettRyland** [comment]
The point is that they shouldn't all be uppercase, only the ones that were added to dev like that should be (though this could be made consistent internally). The simple fix for your current installation is to change the `sounds` folders to match what I posted above.
A bigger issue though is whether or not other folders got capitalised on the latest releases when they shouldn't have been leading to other breakages.

**Comment by bank2014** [comment]
Ok

**Comment by BrettRyland** [comment]
I've just checked the differences between the capitalisations of files in the recent releases and those in dev and it looks like it's only those sounds folders that are affected (a couple of other files were too, but they don't affect anything).
