### ISSUE TITLE
Laser weapon (ABL) firing sound doesn't played as looped audio

### ISSUE THREAD

**Issue by bank2014** [BrettRyland/BDArmory#399]
**Describe the bug**
The title says everything.
and what is ChargeSound for ? it's not used in anywhere in the game

**To Reproduce**
Please provide the steps to reproduce the behaviour:  fire ABL

**Logs**
nothing to see in logs

**Comment by BrettRyland** [comment]
The charge sound is for a new mechanic where weapons take time to charge up before firing. There aren't any stock weapons that use it yet.

I'll check with the others about it being meant to be looped audio or not since the current sound doesn't loop very well and the overheat sound doesn't seem particularly suitable to me (since it's using that of the 50cal turret).

**Comment by bank2014** [comment]
ok

**Comment by BrettRyland** [comment]
This has now been switched in dev to using proper audio looping and a different overheat sound has been added.
