### ISSUE TITLE
Gun sounds not working

### ISSUE THREAD

**Issue by PotatoOrigin** [BrettRyland/BDArmory#413]
I opened BDarmory a few weeks ago and I had tried using the weapons. Most of the guns such as the vulcan, vulcan turret, gau-8, and most cannons didn't have any sound. I had looked and the sound was at max and couldn't find anything that could've been messing with it.

**Comment by BrettRyland** [comment]
This is a known issue due to Visual Studio on Windows changing the capitalisation of some folders on one of the devs machines for the last couple of bug-fix releases while the dev who usually does the releases was unavailable (see https://github.com/BrettRyland/BDArmory/issues/394#issuecomment-1207261130 for how they're supposed to be). It's fixed in dev for the next release.

**Comment by BrettRyland** [comment]
Fixed in the latest release (v1.5.2.0)
