### ISSUE TITLE
Bomb explosions are glitched/creating stock explosions (reposted/updated from PapaJoesSoup repository)

### ISSUE THREAD

**Issue by Sandrik2** [BrettRyland/BDArmory#417]
Issue:

All of BDArmory is working properly, and even the Mk82 and cluster bombs damage targets. My issue is that whenever I do drop a Mk82 or a cluster bomb, it just creates stock explosions, despite still damaging the target. I installed everything correctly, and I am dropping them with the weapons manager as usual.

Test to Reproduce:

I just used a stock Aeris 3A and attached the following to the wings

(2) Cluster Bombs
(2) Mk82 Bombs
(2) JDAM Bombs
(2) Mk82 SnakeEye Bombs

I also attached a weapons manager

All of these weapons DO NOT produce proper explosions when dropped.

They cause explosions that look like this:

![20220821171418_1](https://user-images.githubusercontent.com/49348712/185798026-341ebac6-81cb-400d-ac8d-0de965ea1b9f.jpg)

As opposed to this:

![55673797-bbb58280-587a-11e9-9665-2a523133b620](https://user-images.githubusercontent.com/49348712/185797282-c532d242-eca3-4d6e-8350-df4ddcff26d6.png)

I am using the fire missile button (both tried with an action group and clicking on the bomb), and I am having the same issue

--------------------------------------------------------

Game Information:

KSP Version: 1.12.2 (3167)

BDArmory Version: 1.5.1.2

Physics Range Extender Version: 1.21.0

Mods Currently Installed:

BDArmory
Physics Range Extender

(ModuleManager 4.2.2 is installed)

System Environment:

OS: Windows 10 Home 64bit

System Specs:

GeForce GTX 1050 Ti (Driver Version 516.94)
Intel Core i5-8300h at 2.30GHz base, 3.9 GHz turbo
16GB of DDR4 RAM (15.8GB usable)
Running at 1920 x 1080, 60Hz

--------------------------------------------------------

KSP Logs:

[KSP.log](https://github.com/BrettRyland/BDArmory/files/9389429/KSP.log)

Thank you!

**Comment by BrettRyland** [comment]
OK, I've found and fixed the issue in dev. Thanks!
Note: the cluster bomb is supposed to use the standard explosion, first in the air and then for each submunition when they hit (the sound effect is different for the submunitions though). The other bombs should be using the `explosionLarge` model.

This lead to discovering another bug however, where dropping bombs/firing missiles at the ground with no other craft around can end up with part of the explosion FX appearing offset by the floating origin/Krakensbane adjustments that'll need looking into.

**Comment by BrettRyland** [comment]
It was a bug in BDArmory.
The `explModelPath` and `explSoundPath` in the configs of those parts are defined in the `MissileLauncher` module instead of the `BDExplosivePart` module, but the explosions for those parts are being triggered through the `BDExplosivePart` (not sure when that change happened), which was using the default values. The fix was to internally update the values in `BDExplosivePart` from those in `MissileLauncher` if the `BDExplosivePart` was using the defaults.

The next release of BDA+ should be fairly soon, but you should be able to fix it locally for your current install by copying the
```
  explModelPath = BDArmory/Models/explosion/explosionLarge
  explSoundPath = BDArmory/Sounds/explode1
```
lines from the `MissileLauncher` section of the configs to the `BDExposivePart` section for those parts.

**Comment by Sandrik2** [comment]
@BrettRyland Ok, thank you. I will try the fix locally later, but when the next release comes out I'm just going to nuke everything non-Squad in my GameData folder and just install everything from scratch anyways.

**Comment by Sandrik2** [comment]
@BrettRyland I am running the latest version of BDA and am still having the same issue. Any help?

[KSP.log](https://github.com/BrettRyland/BDArmory/files/9642425/KSP.log)

**Comment by BrettRyland** [comment]
I don't see any error messages in the log file about the models not being found and it looks to be working fine for me. I see that you tested the mk82 and the cluster bomb. The mk82 should be using the larger explosion model, while the cluster bomb uses the standard explosion model.

I've added some extra debugging to the latest dev DLL: [BDArmory.zip](https://github.com/BrettRyland/BDArmory/files/9644260/BDArmory.zip) (overwrite the BDArmory.dll in the BDArmory/Plugins folder with the DLL in the zip file) (note: it may contain some strings that aren't localised since it's just the DLL and not a full install, but should otherwise be compatible with the current release).
If you use that DLL and enable the "Debug Missiles" option (UI Settings → Enable Debugging → Missiles), then you should see something like
```
[LOG 10:06:42.259] [BDArmory.ExplosionFX]: Setting up object pool for explosion of type BDArmory/Models/explosion/explosionLarge with audio BDArmory/Sounds/explode1 for Mk82
[LOG 10:07:36.621] [BDArmory.ExplosionFX]: Setting up object pool for explosion of type BDArmory/Models/explosion/explosion with audio BDArmory/Sounds/explode1 for CBU-87
[LOG 10:07:43.727] [BDArmory.ExplosionFX]: Setting up object pool for explosion of type BDArmory/Models/explosion/explosion with audio BDArmory/Sounds/subExplode
```
in the KSP.log file the first time you create an explosion using a new model or sound.

**Comment by Sandrik2** [comment]
@BrettRyland Here is my KSP.log after enabling Debug Missiles as you specified:
[KSP.log](https://github.com/BrettRyland/BDArmory/files/9648433/KSP.log)


For reference I did two runs of dropping two of every type of bomb from a stock aircraft (and also tested the small explosive warheads on the second run). I also destroyed a couple stock parts in the process. I noticed that the blast awesomeness modifiers are shown as 0 for all of the bombs, while having "normal" values for the stock parts. I don't know if this has anything to do with the issue. I also noticed that the bombs are using the correct audio files (the sounds in-game are working), but I simply cannot generate the large explosion FX as I remember seeing when I played on my older computer. I suspect that it might possibly be an issue with the settings of my graphics cards/physics processing on my computer specifically, since I remember always having this same issue since I got this laptop (regardless of KSP or BDA version). If it would be of any usefulness, I can provide some extra information regarding my graphics driver(s) versions, settings, etc. I have an Acer Nitro 5 AN515-53.

**Comment by BrettRyland** [comment]
The "blast awesomeness" is something from base KSP, not BDArmory. There's a small "part destroyed" explosion hidden inside the main explosion and the size of it determines whether it's an explosion or a puff of smoke, we set it to 0 for the bombs so that it's less noticeable.
The KSP.log is showing that the `explosionLarge` pool is being set up correctly, so the bombs appear to be using the correct models.
How old is the BDA version with the explosion in the second picture, btw? Maybe it's simply an outdated or different model? The `explosionLarge` model looks pretty similar to the standard explosion, just bigger.

**Comment by Sandrik2** [comment]
@BrettRyland I'm not sure how old the picture is exactly, but I transferred it over from my original post on PapaJoesSoup repository so it is a few years old at least. If the explosion model is *supposed* to be just a larger stock explosion, then I do have that in game. However, I always remember in previous versions as well as on all demo footage that the explosions had a different model to the stock, like in the picture. Here's soms dev footage as an example: https://youtu.be/t9WAlJFn6is

**Comment by BrettRyland** [comment]
Looking at that footage from 2016, I think it was using the old explosion model (the normal sized one, not the large one) prior to
```
commit 28b92a4f220d05d3ed14daf30205f17f19d6a216
Author: PapaJoesSoup <joekorinek@cox.net>
Date:   Fri May 18 15:47:18 2018 -0700

    1.2.1.1  Updated explosion assets  This is per SpannerMonkey.
```
I've attached them here: [old_explosion_models.zip](https://github.com/BrettRyland/BDArmory/files/9649868/old_explosion_models.zip)
If you really want to use them, then you can place them in `GameData/BDArmory/Models/explosion/` and adjust the bomb configs to use those instead. They may not appear quite as they originally did due to differences in the time that the emiiters are releasing particles, though, which is more optimised for the current models.

**Comment by Sandrik2** [comment]
@BrettRyland Thank you! The effects are now just as they were before, so my "issue" can be considered solved.
