### ISSUE TITLE
Hellfire missiles, Evading flight mode and cargo bays

### ISSUE THREAD

**Issue by Lgg159** [BrettRyland/BDArmory#449]
**Describe the bug**
I have 3 bugs to share :
1) Hellfire missiles will not get displayed in the weapon manager if the craft also has EMP hellfire missiles, they also have the same name inside de weapon manager, so that could be the cause.

2)The ai flight pilot will keep switching between "engaging" and "evading" mode and prevent itself from attacking when presented against a ennemy craft with turrets, no matter if it is firiing, or even aiming, or even is in Guard mode or not (so the evading mode appears when there is nothing to evade)

3)There are incostistencies with weaponery in cargo bays, the autopillot will sometimes forget to close the doors after switching to another weapon, and therefore closing the doors when it selects it again, causing it to explode mid air. This also sometimes causes the game to crash, with "unexprected stack overflow"

**To Reproduce**
1)Put Hellfire and EMP hellfire missiles on the same craft, with a weapon manager on it. The basic hellfire missile will not appear in the weapon manager UI.

2)Place a ground craft equiped with turrets (haven't tested other yet, in my case it was the Jarnas turret with aim120 missiles on it, alng with a CIWS turret and a tws locking radar). The enemy plane has the autopilot and guard mode activated and is equiped with short range weaponery such as the hidden vulcan gun or rocket dispensers. When getting closer to the enemy craft, (weather it has guard mode activated or not), the plane will rapidly switch between Evading and Engaging mode.

3)Use an aircraft with guard mode and the autopilot, equiped with missiles in a cargo bay (with the custom action configured properly to open the bay doors), in my case, i had AIM120 missiles on a rotary rack inside a mk2 long cargo bay (this configuration is very prone to ships exploding mid air). Give the plane another eapon to switch to, and an ennemy to shoot. When switching to another weapon after using the weapon inside the cargo bay, it will sometimes forget to close it. Though, the plane will sometimes explode mid ait with this configuration, without this malfunction so maybe there's something alse to look at. 

**Expected behaviour**
1) The weapon manager makes a difference between those two kind of missiles

2) The autopilot switches to evading mode only when it is getting attacked (launched bullets, missiles, bombs etc at)

3)The autopilot closes the doors of the cargo bay, and doesn't destroy itslef

**Logs**
[KSP.log](https://github.com/BrettRyland/BDArmory/files/9944839/KSP.log)
In this one, the game crashed after a plane exploded mid air due the bug n°2. (the log is full of exceptions due to another mod sorry for that)

**Comment by Lgg159** [comment]
Oh, and another thing, any type of gun will instantly disable itslef everytime you shoot to break a part of an ennemy craft (which does not happens in guard mode when the ai shoots for you).

**Comment by BrettRyland** [comment]
1. They are displayed, but they're showing up as "AGM-114R" and "EMP Hellfire".
![hellfire](https://user-images.githubusercontent.com/18440126/201433184-6cb325ea-68d3-413e-b8c0-4ac464278040.jpg)

2. Yes, the plane will try to evade when being shot at. The WM will still try to shoot at the current target when possible (e.g., with turrets), even if it's evading, but it will have a hard time lining up fixed guns and narrow bore missiles. You can enable the "Don't Evade My Target" to prevent evading against your current target. With guard mode disabled on the ground turret, I'm not seeing the behaviour you describe, that is, the aircraft doesn't evade the ground turret when it's not actively being fired upon.

3. I see this happening, and will look into it. Using the "In Stock Cargo Bay" toggle instead of the "Custom Bay Toggle" seems to work correctly, however, but you will want to increase the "Drop Time" so that they don't start boosting inside the bay. 
I haven't seen it cause a stack overflow, but if you do get one, please send the KSP.log containing it.

4. I haven't seen any guns disabling themselves in the manner you describe. Can you provide a log and maybe a video (or reproduction steps) of this happening?

**Comment by BrettRyland** [comment]
Looking further in 3., it looks like the "Custom Bay Toggle" is specifically for custom non-stock cargo bays that react to the action group toggle every time it's triggered (stock cargo bays only react if they're fully open or fully closed), which explains this behaviour. So, if you're using stock cargo bays, then use the "In Stock Cargo Bay" option instead.

**Comment by Lgg159** [comment]
Hi, i see you already made quite a few update since my last message, so i might be a little late. Anyways, I've recorded a video for my bug n°4 using the Vulcan turret : 
https://user-images.githubusercontent.com/54372820/204879236-ca3da45a-57e1-4fe7-b40a-731883b49954.mp4
So as you can see, the turret desables itslef each time i destroy a part by shooting at another ship.

I tried recording the bug n°2, but i wasn't able to reproduce it.

And about bug n°4, i checked, and as you said, the two kind of missiles do appear, but as the AGM114 appears as "AGM114R" and that the actual AGM114R appears as "EMP Hellfire", i guess i got confused writing the issue lol. So there's still a mismatch for the name of the regular agm114 getting the name of the emp kind in the weapon manager.

And thank you for adding the weapon cycle key, it's really usefull when playing with a stick or controller when you would rather not use the mouse at all.

**Comment by BrettRyland** [comment]
Ah, I see you're toggling the weapon through the weapon's part window instead of selecting it in the weapon manager window (where it doesn't happen). I can reproduce it locally, so it shouldn't be too hard to debug.

The Hellfire missile and its EMP variant are basically the same missile (i.e., they're both AGM-114R missiles), just with a different payload. I'll ask the guy that made them and get his thoughts regarding the naming of them.

**Comment by Lgg159** [comment]
That's great! Have a nice day then

**Comment by BrettRyland** [comment]
Best to keep the issue open until I've actually fixed it. ;-)
