### ISSUE TITLE
Returned funds from craft recovery do not account for hull material.

### ISSUE THREAD

**Issue by Hidden-Sky** [BrettRyland/BDArmory#461]
**Describe the bug**
Recovering a landed craft does not account for the hull materials. This results in heavy funds losses in career mode due to the default material (aluminum) roughly doubling the price of each part, while the parts only return their stock value upon recovery. Reusable craft are completely non-viable unless made of wood. And no, I am not going to build SSTOs out of wood.

**To Reproduce**
Build a craft at the SPH or VAB. Use the default material (aluminum). Note the cost and amount of funds you have. Launch the craft. Immediately recover the craft. You will only regain a little over half the cost.

**Expected behaviour**
Parts should return their full value upon recovery, or at the very least it should be close. Refurbishing and refueling an SSTO should not be more expensive than building a whole new rocket. That completely defeats the point of an SSTO.

It's also a little ridiculous that the default aluminum material makes parts cost almost double the stock price. Given that this is a space program, it is probably safe to assume that stock part prices are already balanced around most of them being made of aluminum, and not wood. On top of that, it is just flat-out weird to charge extra for using the *default* material.

**Logs**
Will attach later (this was posted from my phone)

**Screenshots**
Will add later (ditto)

**Additional context**
None really, but who is going to stop me from buying mass amounts of wooden parts, and reselling them as "aluminum" for profit? I might just build a wooden SSTO after all.

**Comment by BrettRyland** [comment]
The cost modifier is now fixed in dev.
The formula is:
 - a discount of `(1 - multiplier) * partCost` up to a max of `1000 * (1 - multiplier)` for multipliers less than 1, or
 - a premium of `multipler * partCost` up to a max of `1000 * multiplier` for multipliers greater than 1.
 
However, the amount refunded was being correctly calculated both before and after the fix, so you must have some other mod that's interferring with the refund amount if this isn't working for you.

**Comment by Hidden-Sky** [comment]
Thanks, I'll look into it some more then.
