### ISSUE TITLE
Can't fire missiles or drop bombs

### ISSUE THREAD

**Issue by Jmaniac2323** [BrettRyland/BDArmory#472]
I've changed up the key binding a few times but no matter what I can't get the missiles or bombs to launch

Game version 1.12.3
Mod version 1.5.2.1

**Comment by JovietUnion** [comment]
are ya using action groups to fire them? if so, please double check them. also make sure to add a weapon manager. 
In addition, are you using addons like North Kerbin Dynamics? Because it may not be compatible.

**Comment by BrettRyland** [comment]
First, upgrade to the latest BDA+, there's a lot that has been fixed/improved since v1.5.2.1 (https://spacedock.info/mod/2487/BDArmory%20Plus#changelog).
Then, if you're still having problems, you'll need to provide more details regarding the issue.

Also, the issues tab in github is more for bug reports and feature requests. A more appropriate place to ask for general help in using the mod is https://forum.kerbalspaceprogram.com/index.php?/topic/209092-19x-112x-bdarmory-plus-bda-v1570-2023-01-18
