### ISSUE TITLE
Will BDA+ be ported to KSP 2? I'm asking because the day is literally a month away.

### ISSUE THREAD

**Issue by JovietUnion** [BrettRyland/BDArmory#473]

**Comment by JovietUnion** [comment]
Also, will more weaponry be added, such as the AGM-154A JSOW, or AGM-158 JASSM?

The latter is already in NKDR

**Comment by BrettRyland** [comment]
BDA+ will most likely get ported to KSP2 at some point, but it'll have to wait until I can get my hands on a copy of it and probably play it a bit to get the feel of it first. Also, the KSP devs would need to release an API (similar to https://www.kerbalspaceprogram.com/ksp/api/index.html) for mod makers before any mods for it can be made.

Btw, this sort of question is more suitable for the forum thread, rather than an issue, and has been answered there already https://forum.kerbalspaceprogram.com/index.php?/topic/209092-19x-112x-bdarmory-plus-bda-v1570-2023-01-18/&do=findComment&comment=4221048
