### ISSUE TITLE
Countermeasures not Flowing like Ammo or Fuel

### ISSUE THREAD

**Issue by megaferrari** [BrettRyland/BDArmory#482]
Countermeasures not Flowing naturally, need to be transfered 

Just use any tank or refill for it

**Expected behaviour**
Flow like ammo & fuel

**Logs**
[KSP.log](https://github.com/BrettRyland/BDArmory/files/10701697/KSP.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/5840681/217943809-5409f428-32aa-40be-a3e1-2626241e704e.png)
![image](https://user-images.githubusercontent.com/5840681/217944808-f4f96de7-a3e2-48d9-8b1f-8fa7d0c00bcd.png)

**Comment by BrettRyland** [comment]
This was discussed amongst the devs and the conclusion is that countermeasures shouldn't flow like fuel or ammo since that's not how they work in real life. 
E.g., flares being installed ![flares being installed](https://cdn.discordapp.com/attachments/720423078533791854/1073381546192539678/image.png)

Instead, we plan to add the ability to stagger the firing of countermeasures by giving different CM dispensers of the same type different priorities.
