### ISSUE TITLE
AI Detection Setting

### ISSUE THREAD

**Issue by kman11223344** [BrettRyland/BDArmory#598]
I was flying low-observable aircraft with the radar off (so there wasn't an RWR warning), and as soon as it got into load range of enemy aircraft on the ground, with their radars off and no detection radar or SAM site, they would take off and go after it. I had load range set to around 55 km, so seemingly beyond visual range. 

It would be neat to have a setting or some way to know how the AI is actually detecting enemy aircraft, and possibly adjust the ability to in the BDA settings or something.

**Comment by BillNyeTheIE** [comment]
"Visual Range" is a setting in the guard menu, are you certain you were outside of visual range of all vehicles on that team that were loaded at the time? I can look into this if you can provide some more information about the exact setup involved, I.E. what craft were loaded in, what settings they had, etc. (if you're not using mods apart from BDA+ and BDAe the save file would also be good to include, otherwise a video going through the setup and then showing the issue would be good to have) though I tested it and any aircraft set to standby on their autopilots remained in standby until my aircraft flew into their visual range.

**Comment by kman11223344** [comment]
Ah. I apologize, I did not see that setting. that fixed it. thank you!
