### ISSUE TITLE
Guard mode wont fire weapons

### ISSUE THREAD

**Issue by thetesto23** [BrettRyland/BDArmory#622]
**Description**
While using Guard Mode to attack to attempt to simulate AI dogfights, the two vessels wont shoot one another despite being on different teams. They have guard mode and AI pilot enabled, circle around one another, even lock in their missiles but do not fire any weapons. Same thing happens if I'm piloting one of the vehicles. Even on the ground, they won't shoot. I tried using turrets, too, but that won't work.

**To Reproduce**
1. Use BDArmoryPlus + BDArmoryExtended
2. Use BDA vessel mover to spawn in another vessel.
3. Enable thrusters on both vehicles.
4. Enable guard mode + AI pilot mode on both vehicles (or control one of them)
5. Wait for them to start circling around one another, not fighting.

**Expected behaviour**
I expected both vehicles to start circling one another (of which they do quite fine), and shoot each other using the turrets and guns equipped on the vehicle.

**Logs**
[KSP.log](https://github.com/BrettRyland/BDArmory/files/14475028/KSP.log)

**Screenshots**
Mods enabled:
![download (1)](https://github.com/BrettRyland/BDArmory/assets/147300591/6d4f0d42-f379-474d-9299-075afe753b8f)

**Additional context**
Game version is 1.6.11.0

**Comment by thetesto23** [comment]
Sorry for opening and reopening it multiple times, my mouse bugged out.

**Comment by BrettRyland** [comment]
Your log is showing that an exception is being thrown whenever the WM tries to check the engagement envelope of some weapons, which is preventing it from picking and firing a weapon at a target. Unfortunately, it doesn't show precisely what is causing this exception. However, the weapons from BDA-E generally work fine with BDA+ (when using the latest versions of them), so I suspect that this is due to interference from some other mod(s).
Likely offenders are:
- `NextStarIndustries`, which is not compatible with BDA+ (it depends on BDAc instead, which is incompatible with BDA+).
```
[LOG 00:43:14.703] [ModuleManager] Intercepted a ReflectionTypeLoadException. List of broken DLLs:
NextStarIndustries 1.10.1.1 GameData\NSI\Plugins\NextStarIndustries.dll
```
- `KerbalActuators`, which is throwing an exception whenever you switch vessels. This mod seems intended to only work with the active vessel, but doesn't look to be correctly implemented for switching between vessels in flight mode.
- `Kopernicus`, which is throwing an exception as a reaction to spawning vessels, which may or may not be a problem.
- Additionally, `TweakScale` also throws a few exceptions (which isn't unusual for `TweakScale`) and `HangerExtenderExtended` is missing a dependency (`ToolbarController`), but these shouldn't be affecting weapons.

Also, the log indicates that you're using v1.6.10.0 of BDA+, which isn't the latest version. This shouldn't be a problem, but I'd recommend updating anyway to get the latest fixes.

To isolate the problem, you should run KSP with a reduced set of mods to find which mod is causing BDA+ to break. If the problem persists with just the latest versions of BDA+, BDA-E and their dependencies, then we'll need some more details for reproducing the issue locally.

**Comment by thetesto23** [comment]
Okay, I'll try removing NextStarIndustries, Kerbal Actuaters, Kopernicus, add ToolbarController and update Tweakscale along with BDA+.

**Comment by thetesto23** [comment]
Problem fixed, however planes (for some reason) require the surface operation AI module to use gaurd mode correctly.
