### ISSUE TITLE
Guard Mode Disabled Itself When Exiting to KSC

### ISSUE THREAD

**Issue by PawelW2006** [BrettRyland/BDArmory#625]
**Describe the bug**
When i enable guard mode on a vehicle via the weapon manager it works fine but as soon as i quit to KSC to spawn another vessel or something it turns itself off and has to be re-enabled from the weapons manager or the vessel switcher.

**To Reproduce**
1.- Spawn a Vessel and Enable Guard Mode
2.- Exit to KSC
3.- Go Back to Vessel

**Expected behaviour**
I expected it to stay on as as far as i'm aware guard mode is supposed to be used for sentry style things, you can leave it on and it will fire at any enemy vessels coming within range.

**Logs**
Don't think it's neccessary as it's easily reproducable and not in any way case specific, will provide logs if you insist.

**Screenshots**
Not Easily Screenable, Can provide videos if my description of the issue turns out to not be enough.

**Additional context**
Don't think there's anything more to say.

**Comment by BrettRyland** [comment]
This is intentional to prevent newly spawned vessels from immediately attacking their neighbours prior to competitions getting started or enabling guard mode via the Vessel Switcher window.

It's not necessary to exit flight mode to the KSC in order to spawn new vessels. BDArmory contains a variety of vessel spawning options, either in groups (for competitions/tournaments) via the Vessel Spawner window (`Sp` button) or individually via the built-in Vessel Mover (`VM` button) window.
![Screenshot_20240422_214651](https://github.com/BrettRyland/BDArmory/assets/18440126/313f6f13-f086-49da-bb71-e5d0a2c18715)
